const PRFX = '@chats/';

export const CREATE_NEW_CHAT = `${PRFX}CREATE_NEW_CHAT`;

export const FETCH_CHATS = `${PRFX}FETCH_CHATS`;
export const SAVE_CHATS = `${PRFX}SAVE_CHATS`;

export const SET_ACTIVE_CHAT_ID = `${PRFX}SET_ACTIVE_CHAT_ID`;

export const FETCH_USERS_FOR_CHAT = `${PRFX}FETCH_USERS_FOR_CHAT`;
export const SAVE_USERS_FOR_CHAT = `${PRFX}SAVE_USERS_FOR_CHAT`;

export const SET_UPDATED_CHAT_MESSAGES = `${PRFX}SET_UPDATED_CHAT_MESSAGES`;

export const SEND_MESSAGE = `${PRFX}SEND_MESSAGE`;

export const TOGGLE_COLLAPSE_SIDER_CHAT = `${PRFX}TOGGLE_COLLAPSE_SIDER_CHAT`;
