const PRFX = '@call/';

export const TOGGLE_IS_SHOW_CALL_MODAL = `${PRFX}TOGGLE_IS_SHOW_CALL_MODAL`;
export const SET_IS_SHOW_CALL_MODAL = `${PRFX}SET_IS_SHOW_CALL_MODAL`;

// call settings

export const SET_CALL_SPEAKER = `${PRFX}SET_CALL_SPEAKER`;
export const SET_MIC_DEVICE = `${PRFX}SET_MIC_DEVICE`;
export const SET_CAM_DEVICE = `${PRFX}SET_CAM_DEVICE`;

export const FETCH_DEVICES_LIST = `${PRFX}FETCH_DEVICES_LIST`;

export const SAVE_SPEAKERS_LIST = `${PRFX}SAVE_SPEAKERS_LIST`;
export const SAVE_MICS_LIST = `${PRFX}SAVE_MICS_LIST`;
export const SAVE_CAMS_LIST = `${PRFX}SAVE_CAMS_LIST`;

export const CHECK_CURRENT_SPEAKER = `${PRFX}CHECK_CURRENT_SPEAKER`;

export const SAVE_IS_PLAYING_SPEAKER = `${PRFX}SAVE_IS_PLAYING_SPEAKER`;
