const PRFX = '@auth/';

export const FETCH_LOGIN_BY_GOOGLE = `${PRFX}FETCH_LOGIN_BY_GOOGLE`;
export const FETCH_REGISTER_BY_MAIL_AND_PASSWORD = `${PRFX}FETCH_REGISTER_BY_MAIL_AND_PASSWORD`;
export const FETCH_LOGIN_BY_MAIL_AND_PASSWORD = `${PRFX}FETCH_LOGIN_BY_MAIL_AND_PASSWORD`;

export const SAVE_LOGIN_AUTH = `${PRFX}SAVE_LOGIN_AUTH`;
export const FAIL_LOGIN_AUTH = `${PRFX}FAIL_LOGIN_AUTH`;
export const CLEAR_AUTH = `${PRFX}CLEAR_AUTH`;

export const LOGOUT_REQUEST = `${PRFX}LOGOUT_REQUEST`;

export const SET_UPDATE_PROFILE = `${PRFX}SET_UPDATE_PROFILE`;
export const SAVE_UPDATE_PROFILE = `${PRFX}SAVE_UPDATE_PROFILE`;
