const PRFX = '@profiles/';

export const FETCH_PROFILE_ID = `${PRFX}FETCH_PROFILE_ID`;
export const SAVE_PROFILE_ID = `${PRFX}SAVE_PROFILE_ID`;

export const FETCH_UPDATE_PROFILE_ID = `${PRFX}FETCH_UPDATE_PROFILE_ID`;
export const SAVE_UPDATE_PROFILE_ID = `${PRFX}SAVE_UPDATE_PROFILE_ID`;